### ISSUE TITLE
Add Download App section

### ISSUE THREAD

**Issue by abhinav-adtechs** [GDGVIT/Devfest-2.0#24]
Please add the download app section as soon as the app is ready.

**Comment by rowhitswami** [comment]
@abhinav-adtechs I'd like to take this one.

**Comment by rowhitswami** [comment]
@abhinav-adtechs It will a good idea to use Bootstrap for layout. Can I use its CDN to add Download App section? 
Also, I saw you're using two code block for sponsors, first for the desktop version and another one for mobile or medium-sized devices. This kind of coding standard increases the redundancy of the code. It would a good idea to use Bootstrap for such kind of requirement. It will automatically detect and produce the code according to the size of the device.
Thanks

**Comment by abhinav-adtechs** [comment]
@rowhitswami appreciate your contribution. I'd let the repository moderators to take the call, thanks.
@UjjwalAyyangar please see.

**Comment by aalind0** [comment]
@rowhitswami Please do ! Make sure that nothing breaks in the process. We will merge based on the quality of your pull. Also once you are done, post the screenshots here. Cheers

**Comment by rowhitswami** [comment]
@aalind0 sure..thanks

**Comment by technophilic** [comment]
@rowhitswami bootstrap shouldn't be added to the project. the project already uses [materializecss](http://materializecss.com/). materialize also has a [grid system](http://materializecss.com/grid.html). use that instead.  remove the redundancy if possible.

**Note :**
All non-critical css files are bundled together using [gulp](../blob/master/gulpfile.js#L40) and added asynchronously inside [script.js](../blob/master/src/js/script.js#L473) using [loadCSS](https://github.com/filamentgroup/loadCSS).
this is done to optimize [pagespeed](https://developers.google.com/speed/pagespeed/), adding cdn version to the index.html will be [render-blocking](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css) and will delay the initial render.

PS: you don't have to worry about any of this, just go ahead and modify index.html in src folder.

**Comment by rowhitswami** [comment]
@technophilic Ok I'll use materializecss

**Comment by rowhitswami** [comment]
**Sponsors Section**
<img src="https://preview.ibb.co/mg410m/Screenshot_from_2017_10_18_05_41_44.png" alt="Screenshot_from_2017_10_18_05_41_44" border="0">

**Download App Section**
<img src="https://preview.ibb.co/hRddfm/Screenshot_from_2017_10_18_05_41_50.png" alt="Screenshot_from_2017_10_18_05_41_50" border="0">

**And here mobile view of both changes**
<img src="https://image.ibb.co/dRCtD6/Screenshot_from_2017_10_18_05_42_10.png" alt="Screenshot_from_2017_10_18_05_42_10" border="0">

**Comment by abhinav-adtechs** [comment]
There's no iOS application being built currently, please remove it.

**Comment by rowhitswami** [comment]
@abhinav-adtechs Okay.

**Comment by rowhitswami** [comment]
@abhinav-adtechs removed. Please review PR #26
