### ISSUE TITLE
Add Devfest app link to the button

### ISSUE THREAD

**Issue by rishiraj824** [GDGVIT/Devfest-2.0#34]
Add https://play.google.com/store/apps/details?id=com.gdgvitvellore.devfest17 to the button of play store

**Comment by PrajapatiAnkit** [comment]
can i do it ??

**Comment by PrajapatiAnkit** [comment]
can you please tell me where this link is to be given??
src>index.html
Am i right ??

**Comment by maenad** [comment]
Hey, I am trying to work on this, but it just keeps loading. Not sure why. Also, the link seems to be added already.

**Comment by Geek-ubaid** [comment]
Closing the issue as the project is not ongoing
