### ISSUE TITLE
Mention TechGIG as a Platform Sponsor in the Sponsor's section

### ISSUE THREAD

**Issue by aalind0** [GDGVIT/Devfest-2.0#7]
Make a sub-section named Platform Sponsor inside the Sponsors section and place Techgig there.

**Comment by logichub** [comment]
I am up for this one.

**Comment by aalind0** [comment]
@logichub Go ahead !

**Comment by aalind0** [comment]
@logichub Make a pull request. Also put screenshots here.

**Comment by aalind0** [comment]
@logichub  Can you please remove TechGIG from the common sponsors section as it is already mentioned in the playtform sponsors. Repetition doesnt look good.

**Comment by logichub** [comment]
@aalind0 Sure!

**Comment by logichub** [comment]
Removed the TechGIG logo and replaced it with the NPM logo.
![image](https://user-images.githubusercontent.com/6245858/31534000-5972735a-b00e-11e7-97b4-a0c6b6554dc8.png)

**Comment by technophilic** [comment]
fixed in #9
